INPUT 컴포넌트 개발
Jigeum-lab/web pull request #10
Opened 2024-10-13 10:56 UTC by navyjeongs

JIG-28

# How to develop
div안에 input을 넣어서 검색 아이콘 및 버튼을 추가했습니다.

input에 아이콘들은 absolute로도 배치할 수 있었지만 반응형등이 들어가면 별로인것 같아서 이와 같이 작업했습니다.

따라서 input외 영역을 클릭했을때도 포커스 해야해서 ref 사용했습니다.

# Result

<img width="414" alt="스크린샷 2024-10-13 오후 6 24 31" src="https://github.com/user-attachments/assets/b4310e59-c14d-44f0-ac12-19ef03a4b937">

2024-10-13 11:29 UTC, sgd122 requested changes
고생하셨습니다.
현재 에디터툴에 스타일린트가 적용되지않으신것 같습니다.
확인해주시고, 나머지부분은 아래내용 확인해주세요 👍

2024-10-13 11:29 UTC, sgd122 commented on packages/ui/src/components/input/input.tsx
> +        </Button>
입력 글자는 props로 빼두시고 입력안하면 기본값으로 '입력' 으로 나오게하고, props에 입력값이 들어오면 그 text로 나오게 변경해주세요.

2024-10-13 11:29 UTC, sgd122 commented on packages/ui/src/components/input/index.module.scss
> +
커서색상 `caret-color` 부분도 확인해주세요.

2024-10-13 11:29 UTC, sgd122 commented on packages/ui/src/components/input/index.ts
> +export { Input } from './input';
InputProps도 export 추가해주세요.
`export type { InputProps } from './input';`

2024-10-13 11:29 UTC, sgd122 commented on packages/ui/src/components/input/input.tsx
> +        <Button size="small" variant="filled">
disabled일때 버튼클릭안되게하는부분도 확인하신건가요?

2024-10-13 11:29 UTC, sgd122 commented on packages/ui/src/components/input/index.module.scss
![image](https://github.com/user-attachments/assets/f18cc5a3-9d60-4f09-b74a-76a363eab76d)

p1; stylelint가 맞지않습니다.

2024-10-13 11:29 UTC, sgd122 commented on packages/ui/src/components/input/input.tsx
> +  showRightIcon: boolean;
```suggestion
  showLeftIcon?: boolean;
  showRightIcon?: boolean;
```
showLeftIcon, showRightIcon는 필수입력일 필요는 없을것 같습니다.
기본값을 false로 지정해주세요.

2024-10-13 11:29 UTC, sgd122 commented on packages/ui/src/components/input/input.tsx
> +interface InputProps extends InputHTMLAttributes<HTMLInputElement> {
p5; name이라는 인자가 input의 엘리먼트로 기본적으로 있긴하지만
저희 컴포넌트에서는 필수입력으로 하고싶습니다.
혹시 동의(?)하신다면 필수입력형태로 추가해주신다면 감사할것 같습니다 ㅎㅎ

2024-10-13 11:29 UTC, sgd122 commented on packages/ui/src/components/input/input.tsx
> +        isInvalid && styles.invalid,
p1;
isInvalid일때 포커스가 되면 포커스가 더 우선순위로 동작됩니다.
isInvalid이 더 우선순위가 높아야하지않을까요?

2024-10-13 11:30 UTC, sgd122 commented on packages/ui/src/components/input/input.tsx
> +        <Button size="small" variant="filled">
그리고 버튼클릭 이벤트도 있어야하지않나요?

2024-10-20 04:20 UTC, navyjeongs commented on packages/ui/src/components/input/input.tsx
> +        </Button>
[b4fd46b](https://github.com/Jigeum-lab/web/pull/10/commits/b4fd46bbfecfbe9b12c8d129438b70bd5a8d778c) 텍스트를 받을 수 있도록 변경하였습니다!

2024-10-20 04:20 UTC, navyjeongs commented on packages/ui/src/components/input/index.module.scss
> +
[58d77ba](https://github.com/Jigeum-lab/web/pull/10/commits/58d77ba0f64bd05d9718be410cd3d05e61919777)

커서 색상 변경하였습니다

2024-10-20 04:21 UTC, navyjeongs commented on packages/ui/src/components/input/index.ts
> +export { Input } from './input';
[32fa3c4](https://github.com/Jigeum-lab/web/pull/10/commits/32fa3c463a8f0ba0b4d237bb64bda3dc7bc8f7c5)

타입 export하였습니다

2024-10-20 04:21 UTC, navyjeongs commented on packages/ui/src/components/input/input.tsx
> +        <Button size="small" variant="filled">
[45f3c31](https://github.com/Jigeum-lab/web/pull/10/commits/45f3c31590245ef1a51eb92b5df828b9c9b9dc8f)

버튼 disabled 처리를 하였습니다

2024-10-20 04:22 UTC, navyjeongs commented on packages/ui/src/components/input/input.tsx
> +        <Button size="small" variant="filled">
버튼 클릭 이벤트 같은경우 input props에 onClick이 있어서 생략하였는데 명시적으로 buttonOnClick을 추가하는것이 좋을까요??

2024-10-20 04:22 UTC, navyjeongs commented on packages/ui/src/components/input/index.module.scss
[857f34c](https://github.com/Jigeum-lab/web/pull/10/commits/857f34cef72989a09c64a27f103a335470316622)

엇 확장 설치했는데 안되어있네요!

적용하였는데 한번만 확인부탁드립니다.

2024-10-20 04:22 UTC, navyjeongs commented on packages/ui/src/components/input/input.tsx
> +  showRightIcon: boolean;
[ab9b9ff](https://github.com/Jigeum-lab/web/pull/10/commits/ab9b9ff987bd0e3191e3e1ab1c27c54c9114ab4e)

옵셔널로 변경하였습니다

2024-10-20 04:24 UTC, navyjeongs commented on packages/ui/src/components/input/input.tsx
> +interface InputProps extends InputHTMLAttributes<HTMLInputElement> {
[c16c2ff](https://github.com/Jigeum-lab/web/pull/10/commits/c16c2ff0d92b894de9fa671125de49b14986f9ce)

필수로 하였습니다!
혹시 name을 필수로 하면 좋은점을 알려주실수 있으신가요!

2024-10-20 04:25 UTC, navyjeongs commented on packages/ui/src/components/input/input.tsx
> +        isInvalid && styles.invalid,
이 부분은 제가 의도한 부분이긴하였습니다.

invalid일때 포커스하면 포커스가 보이도록 하였는데

invalid가 더 높은 우선 순위로 동작하도록 변경하였습니다.

<img width="419" alt="스크린샷 2024-10-20 오후 1 25 23" src="https://github.com/user-attachments/assets/1c208e68-8b32-444a-8c87-6bbde1290ebd">

2024-10-20 04:26 UTC, navyjeongs commented on packages/ui/src/components/input/input.tsx
> +        <Button size="small" variant="filled">
버튼과 관련해서 논의해야할 부분이 버튼에 disabled을 넘기니 버튼 자체 색상이 변경되는데 어떻게 처리하는 것이 좋을까요?
<img width="411" alt="스크린샷 2024-10-20 오후 1 08 30" src="https://github.com/user-attachments/assets/b8f6faed-d469-408a-bc29-21ea98c7cc4c">

2024-10-20 08:03 UTC, sgd122 commented on packages/ui/src/components/input/input.tsx
> +        isInvalid && styles.invalid,
음....그럴수도있겠네요.
한번 사용해보다가 기존처럼 사용하는게더 용이하다고 생각하면 변경 고려해보면 좋을것같네요.

2024-10-20 08:08 UTC, sgd122 commented on packages/ui/src/components/input/input.tsx
> +        <Button size="small" variant="filled">
`buttonProps: ButtonProps` 형태로 버튼 컴포넌트의 props를 그대로 넘기게끔 한다면 자율성이 증가할것으로 보여집니다.

2024-10-20 08:12 UTC, sgd122 commented on packages/ui/src/components/input/input.tsx
> +        <Button size="small" variant="filled">
그렇게되면 자연스럽게 `text?: string;` 추가한부분도 사용할필요없이 buttonProps에서 통제가 가능할것으로 보여지구요.

2024-10-20 08:12 UTC, sgd122 commented on packages/ui/src/components/input/index.module.scss
![image](https://github.com/user-attachments/assets/e8f8b905-46af-4a27-9576-de85c02f619f)
아래 사진처럼 변경되어야합니다.
이부분 제외하면 잘 되어있는것 같습니다 :)

![image](https://github.com/user-attachments/assets/4cc2bcb4-4e0f-4551-b06c-02e9306fa165)

2024-10-20 08:14 UTC, sgd122 commented on packages/ui/src/components/input/input.tsx
> +interface InputProps extends InputHTMLAttributes<HTMLInputElement> {
폼데이터 전송할때 누락이 적을것이며, 웹 접근성이 용이해집니다 :)

2024-10-20 10:54 UTC, navyjeongs commented on packages/ui/src/components/input/index.module.scss
스타일린트 옵션을 한번더 확인해봐야겠네요!
감사합니다
[d6649f3](https://github.com/Jigeum-lab/web/pull/10/commits/d6649f3297b2d89ae0ea09d9d72035b3bc85037d)

2024-10-20 10:55 UTC, navyjeongs commented on packages/ui/src/components/input/input.tsx
> +        <Button size="small" variant="filled">
[2d359ac](https://github.com/Jigeum-lab/web/pull/10/commits/2d359ac2836359cfdaf5854f09ecd5c011819797)

사실 그렇데되면 showRightIcon이라는 props도 buttonProps 여부로 판별할 수 있을것 같아 다음과 같이 작업하였습니다

2024-10-20 11:21 UTC, sgd122 commented on packages/ui/src/components/input/input.tsx
> +        <Button size="small" variant="filled">
showRightIcon은 해당 버튼부분의 존재여부를 결정하는 인자이고,
buttonProps는 버튼의 스타일 여부를 지정하는 인자라서
두개가 독립적으로 존재해야하지않을까요?

2024-10-20 11:34 UTC, navyjeongs commented on packages/ui/src/components/input/input.tsx
> +        <Button size="small" variant="filled">
아하 제 생각에는 buttonProps가 있는데 showRightIcon이 false면 안보여주는 케이스가 있다고 생각했었습니다

아래와 같이 다시 showRightIcon을 Optional로 받을 수 있도록 추가하였습니다
[ed6652b](https://github.com/Jigeum-lab/web/pull/10/commits/ed6652b850aaf9360f08d94dc4bace6bf100a398)

2024-10-20 11:41 UTC, sgd122 approved these changes

2024-10-20 12:51 UTC, merged