[JIG-57] 상세 개요 컴포넌트 개발
Jigeum-lab/web pull request #20
Opened 2024-10-28 13:33 UTC by SeungJin051

# Result
개요 컴포넌트를 개발하였습니다.

- `useScreenSize`를 활용하여 모바일과 데스크탑 컴포넌트의 속성 값을 분리하였습니다.
- SCSS에서는 모바일과 데스크탑에 맞는 스타일을 적용하기 위해 `include`를 사용하였습니다.

(항상 좋은 답변과 리뷰 감사합니다!😊)

2024-10-28 13:49 UTC, sgd122 requested changes
구현된 코드보다는 구조적인 부분에서의 문제가 조금 있는것 같습니다.
코멘트 확인해보시면 자세히 나와있습니다.

**전체적으로 아래와같은 구조에 맞춰서 나오도록 해주세요.**
```
page.tsx
view.tsx
hooks
  - index.ts
  - useProjectDetailViewModel.tsx
_components
  - ProjectOverview
    - index.ts
    - ProjectOverview.tsx
    - index.module.scss 
```

이 구조로 하게되면
```
const { data, error, isLoading } = useGetProjectDetail(slug);
.
.
.
const projectData = (data as unknown as ProjectApiResponse)?.data;
```
여기까지에 대한 부분들처럼 data를 가공하고 action을 취하는 부분들에 대해서는 useProjectDetailViewModel에 들어가게되고 그걸 페이지단에서 가져다쓰는형태가 되겠죠?

ex) `auth/signin/view.tsx` 페이지 참조해주세요.

2024-10-28 13:49 UTC, sgd122 commented on apps/web/src/app/[lang]/project/[slug]/page.tsx
> +  const queryClient = getGetProjectDetailQueryKey();
```suggestion
  const queryClient = getQueryClient();
```
queryClient를 선언하는 부분입니다. 코드자체가 잘못되었습니다.

2024-10-28 13:49 UTC, sgd122 commented on apps/web/src/app/[lang]/project/[slug]/page.tsx
> +    ...getGetProjectListQueryOptions(),
제가 HydratePage를 사용하라고 한 이유는 client에서의 fetch를 서버에서 미리 fetch하고자 하기 위한 용도입니다.
그렇기때문에 client에서 params로 넣어던 `params.slug` 가 동일하게 들어가야합니다.

2024-10-28 13:49 UTC, sgd122 commented on apps/web/src/app/[lang]/main/_components/ProjectOverview/ProjectOverview.tsx
> +  }
SSR이기때문에 loading자체가 없습니다.
코드 삭제해주세요.

2024-10-28 13:49 UTC, sgd122 commented on apps/web/src/app/[lang]/main/_components/ProjectOverview/ProjectOverview.tsx
> +  if (error) {
error는 별도로 처리할 예정이지만 일단은 별도로 코멘트 남기진 않겠습니다.

2024-10-28 13:49 UTC, sgd122 commented on apps/web/src/app/[lang]/project/[slug]/page.tsx
> +      <ProjectOverview />
`_component/ProjectOverview`를 page.tsx에서 바로 호출하는 형태가 아니라

page.tsx와 동일한 레벨에 `view.tsx` 파일을 만들고 거기서 별도로 컴포넌트화 하는 형태로 해주세요.
`view.tsx`에서 필요한 컴포넌트들을 지금처럼 `_component/ProjectOverview` 등으로 만들어서 호출...이해하셨나요?

2024-10-28 13:52 UTC, sgd122 commented
근데 애초에 왜 main에 있는걸 프로젝트에서 가져다쓰는거죠?

2024-10-28 17:48 UTC, SeungJin051 commented on apps/web/src/app/[lang]/project/[slug]/page.tsx
> +  const queryClient = getGetProjectDetailQueryKey();
넵 확인했습니다.

<img width="277" alt="스크린샷 2024-10-29 오전 2 47 48" src="https://github.com/user-attachments/assets/d92b872c-6d56-4f4d-97d7-ca3f41916e04">

구조는 이렇게 잡으면 될까요?

2024-10-28 17:54 UTC, SeungJin051 commented on apps/web/src/app/[lang]/main/_components/ProjectOverview/ProjectOverview.tsx
> +  }
기본을 놓쳤네요..
넵!

2024-10-28 17:54 UTC, SeungJin051 commented on apps/web/src/app/[lang]/main/_components/ProjectOverview/ProjectOverview.tsx
> +  if (error) {
넵 알겠습니다!

2024-10-28 18:01 UTC, SeungJin051 commented on apps/web/src/app/[lang]/project/[slug]/page.tsx
> +      <ProjectOverview />
제가 프로젝트 구조를 파악하지 못했던 것 같네요..

`page.tsx와 동일한 레벨에 view.tsx 파일을 만들고 컴포넌트화 하는 형태로` 진행해보겠습니다!

질문) 
현재는
```typescript
import ProjectOverview from '../_components';

const SlugPage = async () => {
  //  slug를 빈 값으로 놓아도 되나요? 아니면 다른 방법이 있을까요..?
  return <ProjectOverview slug={''} />;
};
export default SlugPage;
```
로 [slug]안에서 컴포넌트를 불러와서 처리 했는데...
동적 라우팅의 page.tsx는 어떻게 처리하면 되나요?

2024-10-29 02:42 UTC, sgd122 commented on apps/web/src/app/[lang]/project/[slug]/page.tsx
> +    ...getGetProjectListQueryOptions(),
아뇨...Next.js 사용 및 개념에 대한 이해도를 끌어올리셔야하는 부분들이 많이 보이는것 같습니다...
이런식으로 사용하라는 의미였습니다.

```typescript
const { slug } = params;
  const queryClient = getQueryClient();
  await queryClient.prefetchQuery({
    ...getGetProjectDetailQueryOptions(slug),
  });

  return (
    <HydratePage queryClient={queryClient}>
      <ProjectOverViewView />
    </HydratePage>
  );
```

2024-10-29 02:51 UTC, sgd122 commented on apps/web/src/app/[lang]/project/[slug]/page.tsx
> +  const queryClient = getGetProjectDetailQueryKey();
지금 왜 `/overview`,`/overview/[slug]`  페이지를 두개 만들고 있는건가요?

```typescript
overview
  [slug]
     page.tsx
     view..tsx
     hooks/
     _components/     
```
이런식으로 내가 만드는 페이지안에서만 폴더랑 만들어서 처리하라는 의미입니다.

2024-10-29 02:52 UTC, sgd122 commented on apps/web/src/app/[lang]/project/[slug]/page.tsx
> +      <ProjectOverview />
https://github.com/Jigeum-lab/web/pull/20#discussion_r1820000066

위 답변으로 대체하겠습니다.

2024-10-30 09:05 UTC, sgd122 approved these changes

2024-10-30 11:50 UTC, merged